version: 2

sources:
  - name: staging
    database: kafka-streaming-418018 # BigQuery project id
    schema: company_house # BigQuery data set
    tables:
      - name: company_house_core_partitioned
      - name: company_house_stream
  - name: production
    database: kafka-streaming-418018 # BigQuery project id
    schema: prod # BigQuery data set
    tables:
      - name: get_last_timestamp
      - name: snapshot_streamed_data