version: 2

sources:
  - name: staging
    database: kafka-streaming-418018 # BigQuery project id
    schema: company_house # BigQuery data set

    tables:
      - name: company_house_core_partitioned
      - name: company_house_stream